#!/bin/python3
import sys
import signal
# import locale
# import gettext
# localedir = "@localedir@"
# locale.bindtextdomain("list", localedir)
# locale.textdomain("list")
# gettext.install("list", localedir)
pkgdatadir = "/app/share/list"

if __name__ == "__main__":
    sys.path.insert(1, pkgdatadir)
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    from gi.repository import Gio
    resource = Gio.Resource.load(pkgdatadir + '/io.github.mrvladus.List.gresource')
    resource._register()

    from list import main
    app = main.Application()
    sys.exit(app.run(sys.argv))
